name: flutter_flavor_ui_example
description: Example app demonstrating the flutter_flavor_ui package.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.8.0
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_flavor_ui:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
